

services:
  db:
    image: postgres:14
    container_name: ganjadao-db
    restart: always
    environment:
      POSTGRES_DB: ganjadao
      POSTGRES_USER: ganja
      POSTGRES_PASSWORD: senhasegura
    volumes:
      - postgres-data:/var/lib/postgresql/data

  ganjadao-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ganjadao-app
    restart: always
    environment:
      NODE_ENV: production
      SESSION_SECRET: ${SESSION_SECRET}
      DATABASE_URL: postgres://ganja:senhasegura@db:5432/ganjadao
    labels:
      - "traefik.enable=true"
      # redireciona HTTP→HTTPS
      - "traefik.http.routers.http-to-https.rule=Host(`ganjadao.dpo2u.com`)"
      - "traefik.http.routers.http-to-https.entrypoints=web"
      - "traefik.http.routers.http-to-https.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # rota principal
      - "traefik.http.routers.ganjadao.rule=Host(`ganjadao.dpo2u.com`)"
      - "traefik.http.routers.ganjadao.entrypoints=websecure"
      - "traefik.http.routers.ganjadao.tls.certresolver=myresolver"
      - "traefik.http.services.ganjadao.loadbalancer.server.port=3000"
    networks:
      - dao_default
    depends_on:
      - db

volumes:
  postgres-data:
    external: false

networks:
  dao_default:
    external: true