services:
  ganjadao-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ganjadao:latest
    container_name: ganjadao-app
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - "5050:3000"
    volumes:
      - ganjadao-logs:/app/logs

volumes:
  ganjadao-logs:
