sservices:
  ganjadao-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ganjadao-app
    restart: always
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ganjadao.rule=Host(`ganjadao.app`)"
      - "traefik.http.routers.ganjadao.entrypoints=websecure"
      - "traefik.http.routers.ganjadao.tls.certresolver=myresolver"
      - "traefik.http.services.ganjadao.loadbalancer.server.port=3000"
    networks:
      - dao_default

networks:
  dao_default:
    external: true
