services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: always
    command:
      - --api.insecure=true                             # dashboard sem auth (remova em produção)
      - --providers.docker=true                         # lê containers via labels
      - --entrypoints.web.address=:80                   # HTTP
      - --entrypoints.websecure.address=:443            # HTTPS
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.email=seu-email@exemplo.com
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"                                     # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt                       # armazena os certificados
    networks:
      - web

  ganjadao-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ganjadao:latest
    container_name: ganjadao-app
    restart: always
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      # redireciona HTTP → HTTPS
      - "traefik.http.routers.ganjadao-http.rule=Host(`ganjadao.app`)"
      - "traefik.http.routers.ganjadao-http.entrypoints=web"
      - "traefik.http.routers.ganjadao-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # rota HTTPS
      - "traefik.http.routers.ganjadao.rule=Host(`ganjadao.app`)"
      - "traefik.http.routers.ganjadao.entrypoints=websecure"
      - "traefik.http.routers.ganjadao.tls.certresolver=myresolver"
      # expõe a porta interna do Node
      - "traefik.http.services.ganjadao.loadbalancer.server.port=3000"
    networks:
      - web

volumes:
  letesencrypt: {}  # onde o Traefik guarda os certificados
  ganjadao-logs: {}

networks:
  web:
    driver: bridge
